"""new models

Revision ID: 18d2fe42c328
Revises: 
Create Date: 2025-01-16 23:15:27.074205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18d2fe42c328"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("media_url", sa.String(length=1024), nullable=False),
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("media_url", sa.String(length=1024), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=1024), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("tasks")
    op.drop_table("events")
    # ### end Alembic commands ###
